name: Simba
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.5.3
  image_picker: ^1.0.0
  permission_handler: ^11.3.0
  flutter_expandable_fab: ^2.5.2
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  mobile_scanner: ^5.1.1
  flutter_slidable: ^3.1.2
  card_loading: ^0.3.0
  flutter_card_swiper: ^7.0.2
  flutter_local_notifications: ^17.2.2
  intl: ^0.20.2
  excel: ^4.0.6
  file_picker: ^5.2.7
  fl_chart: ^0.66.0
  dio: ^5.9.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4
  sqflite: ^2.3.0
  path: ^1.8.3
  # qr_code_scanner: ^1.0.1
  # mime: ^1.0.4
  # intl: ^0.18.0
  # custom_refresh_indicator: ^4.0.1
  # url_launcher: ^6.3.1
  # flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_icons:
    image_path: "assets/images/SIMAP_LOGO_SPLASH.png"
    android: true
    ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGO_INDOCEMENT.jpg
    - assets/images/icons/BOX.png
    - assets/images/icons/warning.png
    - assets/images/dummy_logo_indocemenet.png
    - assets/images/logo_she.png
    - assets/images/placeholder.png
    - assets/images/icons/BOX.png
    - assets/images/icons/alert.png
    - assets/images/icons/welcome_page/registered_asset.png
    - assets/images/icons/welcome_page/unscanned_asset.png
    - assets/images/icons/welcome_page/damage_asset.png
    - assets/images/icons/welcome_page/lost_asset.png
    - assets/images/indocement_logo.png
    - assets/placeholder.png
    - assets/images/icons/damaged_page/warning.png
    - assets/images/icons/damaged_page/warning_mail.png
    - assets/images/icons/damaged_page/camera.png
    - assets/images/icons/damaged_page/upload.png
    - assets/images/icons/activity_page/category.png
    - assets/images/icons/activity_page/location.png
    - assets/images/icons/activity_page/status.png
    - assets/images/icons/activity_page/create_at.png
    - assets/images/icons/activity_page/update_at.png
    - assets/images/icons/activity_page/product.png
    - assets/images/icons/activity_page/research.png
    - assets/images/icons/lost_page/warning.png
    - assets/images/icons/welcome_page/analytic.png
    - assets/images/icons/welcome_page/box_icon.png
    - assets/images/icons/gif/SIMAP_LOGO.gif
    - assets/images/SIMAP.png
    - assets/images/icons/welcome_page/learn.png
    - assets/images/icons/activity_page/alert.png
    - assets/images/icons/activity_page/damage.png
    - assets/images/icons/barcode_scan.png
    - assets/images/icons/image.png
    - assets/images/icons/activity_page/searching.png
    - assets/images/icons/activity_page/scan.png
    - assets/images/icons/activity_page/image.png
    - assets/images/icons/activity_page/view.png
    # - E:\Flutter Project\simba_indocement\simba\android\app\src\main\res\mipmap-hdpi\image.png
    # - assets/lottie/Inventory.lottie
    # - assets/lottie/Logistic.lottie
    # - assets/lottie/Trader.lottie

    # - assets/lottie/idea.gif
    # - assets/images/icons/registered_assets.png
    # - assets/images/icons/unscanned_assets.png
    # - assets/images/icons/lost_assest.png
    # - assets/images/icons/damage_asset.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Light.ttf

    - family: Telkomsel Batik Sans
      fonts:
        - asset: assets/fonts/Telkomsel Batik Sans Regular.otf

    - family: Maison Bold
      fonts:
        - asset: assets/fonts/fonnts.com-Maison_Neue_Bold.ttf

    - family: Maison Book
      fonts:
        - asset: assets/fonts/fonnts.com-Maison_Neue_Book.ttf

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/SIMAP_LOGO_SPLASH.png"
  android: true
  ios: true
  web: false
